id: P009503
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16570
  title: ཤང་ཤང་སྨན་རྫོང་།
  author: ''
  volumes:
    b6d066b4108845f19e869f1e0b4e8f4d:
      image_group_id: I2PD18062
      title: ''
      volume_number: 1
      total_pages: 536
